apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deployment
  labels:
    app: capstone-app
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: capestone-app
  template:
    metadata:
      labels:
        app: capestone-app
    spec:
      containers:
      - name: capstone-app
        image: graupma/capstone:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: capstone-service
spec:
  selector:
    app: capstone-app
  ports:
    - protocol: TCP
      port: 80 #arbitrary port
      targetPort: 8080 #application port

