apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  labels:
    app: capstone
spec:
  selector:
    matchLabels:
      app: capstone
      tier: website
  replicas: 3
  template:
    metadata:
      labels:
        app: capstone
        tier: website
    spec:
      containers:
      - name: capstone-app
        image: graupma/capstone:latest
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: website
  labels:
    app: capstone
    tier: website
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  #type: NodePort
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the website service.
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: capstone
    tier: website
