apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKS-capstone-cluster
  region: eu-central-1

nodeGroups:
  - name: ng-capstone
    instanceType: t2.small
    desiredCapacity: 3
    ssh: # use existing EC2 key
      publicKeyName: test-ec2