# Python CircleCI 2.0 configuration file
#
version: 2
jobs:
  build:
    docker:
      - image: python:3.7.3-stretch

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.6.0/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - run:
         name: install docker
         command: |
            apt-get update
            echo "###############################################"
            apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y
            echo "###############################################"
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
            echo "###############################################"
            apt-key fingerprint 0EBFCD88
            echo "###############################################"
            add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            echo "###############################################"
            apt-get update
            echo "###############################################"
            apt-get install docker-ce docker-ce-cli containerd.io -y
            echo "###############################################"
            docker --version

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
      - run:
          name: build docker image
          command: |
            . venv/bin/activate
            docker build --tag=capstone:latest .

      - run:
          name: upload docker image
          command: |
            . venv/bin/activate
            dockerpath=graupma/capstone
            echo "Docker ID and Image: $dockerpath"
            echo "$DOCKER_PW" | docker login -u $DOCKER_USERNAME --password-stdin
            docker image tag capstone $dockerpath
            docker image push $dockerpath

